name: 2020-10-illumidesk-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - alembic=1.4.2
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - atk=2.36.0
  - atk-1.0=2.36.0
  - attrs=20.1.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - bleach=3.1.5
  - blinker=1.4
  - boost-cpp=1.72.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.16.1
  - ca-certificates=2020.6.20
  - cairo=1.16.0
  - certifi=2020.6.20
  - certipy=0.1.3
  - cffi=1.14.1
  - cfitsio=3.470
  - chardet=3.0.4
  - conda=4.8.3
  - conda-package-handling=1.7.0
  - configurable-http-proxy=4.2.1
  - cryptography=3.0
  - curl=7.71.1
  - dbus=1.13.6
  - dcw-gmt=1.1.4
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.9
  - ffmpeg=4.3.1
  - fftw=3.3.8
  - fontconfig=2.13.1
  - freetype=2.10.2
  - freexl=1.0.5
  - fribidi=1.0.10
  - gdal=3.0.4
  - gdk-pixbuf=2.38.2
  - geos=3.8.1
  - geotiff=1.5.1
  - gettext=0.19.8.1
  - ghostscript=9.22
  - giflib=5.2.1
  - glib=2.66.0
  - gmp=6.2.0
  - gmt=6.1.1
  - gnuplot=5.2.7
  - gnutls=3.6.13
  - gobject-introspection=1.64.1
  - graphicsmagick=1.3.35
  - graphite2=1.3.13
  - gshhg-gmt=2.3.7
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - gtk2=2.24.32
  - harfbuzz=2.4.0
  - hdf4=4.2.13
  - hdf5=1.10.5
  - icu=64.2
  - idna=2.10
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - ipykernel=5.3.4
  - ipython=7.17.0
  - ipython_genutils=0.2.0
  - jedi=0.17.2
  - jinja2=2.11.2
  - jpeg=9d
  - json-c=0.13.1
  - json5=0.9.4
  - jsonschema=3.2.0
  - jupyter_client=6.1.6
  - jupyter_core=4.6.3
  - jupyter_telemetry=0.0.5
  - jupyterhub=1.1.0
  - jupyterhub-base=1.1.0
  - jupyterlab_server=1.2.0
  - kealib=1.4.13
  - krb5=1.17.1
  - lame=3.100
  - ld_impl_linux-64=2.34
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libcurl=7.71.1
  - libdap4=3.20.6
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.2.1
  - libgd=2.2.5
  - libgdal=3.0.4
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.8.0
  - libllvm9=9.0.1
  - libnetcdf=4.7.4
  - libnghttp2=1.41.0
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libpq=12.3
  - libsodium=1.0.18
  - libspatialite=4.3.0a
  - libssh2=1.9.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libuv=1.34.0
  - libwebp=1.0.2
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - mako=1.1.3
  - markupsafe=1.1.1
  - mistune=0.8.4
  - nbconvert=5.6.1
  - nbformat=5.0.7
  - nbresuse=0.3.6
  - ncurses=6.2
  - nettle=3.4.1
  - nodejs=13.13.0
  - notebook=6.1.3
  - numpy=1.19.1
  - oauthlib=3.0.1
  - openh264=2.1.1
  - openjpeg=2.3.1
  - openssl=1.1.1g
  - packaging=20.4
  - pamela=1.0.0
  - pandoc=2.10.1
  - pandocfilters=1.4.2
  - pango=1.42.4
  - parso=0.7.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.2.2
  - pixman=0.38.0
  - poppler=0.67.0
  - poppler-data=0.4.9
  - postgresql=12.3
  - proj=7.0.0
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.6
  - psutil=5.7.2
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pycosat=0.6.3
  - pycparser=2.20
  - pycurl=7.43.0.5
  - pygments=2.6.1
  - pyjwt=1.7.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - python-editor=1.0.4
  - python-json-logger=0.1.11
  - python_abi=3.8
  - pyzmq=19.0.2
  - qt=5.12.5
  - readline=8.0
  - requests=2.24.0
  - ruamel.yaml=0.16.10
  - ruamel.yaml.clib=0.2.0
  - ruamel_yaml=0.15.80
  - send2trash=1.5.0
  - setuptools=49.6.0
  - six=1.15.0
  - sqlalchemy=1.3.19
  - sqlite=3.33.0
  - tbb=2020.2
  - terminado=0.8.3
  - testpath=0.4.4
  - tiledb=1.7.0
  - tk=8.6.10
  - tornado=6.0.4
  - tqdm=4.48.2
  - traitlets=4.3.3
  - tzcode=2020a
  - urllib3=1.25.10
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.35.1
  - x264=1!152.20180806
  - xerces-c=3.2.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.0
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - ansi2html==1.5.2
    - appdirs==1.4.4
    - autopep8==1.5.3
    - blis==0.4.1
    - boto==2.49.0
    - boto3==1.14.63
    - botocore==1.17.63
    - brotli==1.0.9
    - catalogue==1.0.0
    - chart-studio==1.1.0
    - click==7.1.2
    - colorlover==0.3.0
    - cufflinks==0.17.3
    - cycler==0.10.0
    - cymem==2.0.3
    - dash==1.12.0
    - dash-core-components==1.10.0
    - dash-html-components==1.0.3
    - dash-renderer==1.4.1
    - dash-table==4.7.0
    - datetime==4.3
    - dill==0.3.2
    - docker==4.3.1
    - docutils==0.15.2
    - flake8==3.8.3
    - flask==1.1.2
    - flask-compress==1.5.0
    - fredapi==0.4.2
    - funcy==1.14
    - future==0.18.2
    - gensim==3.8.3
    - iniconfig==1.0.1
    - ipywidgets==7.5.1
    - itsdangerous==1.1.0
    - jmespath==0.10.0
    - joblib==0.16.0
    - jupyter==1.0.0
    - jupyter-console==6.2.0
    - jupyter-contrib-core==0.3.3
    - jupyter-contrib-nbextensions==0.5.0
    - jupyter-dash==0.3.0
    - jupyter-highlight-selected-word==0.2.0
    - jupyter-latex-envs==1.4.6
    - jupyter-nbextensions-configurator==0.4.1
    - jupyterlab==2.2.4
    - kiwisolver==1.2.0
    - lxml==4.5.2
    - matplotlib==3.3.0
    - mccabe==0.6.1
    - more-itertools==8.5.0
    - murmurhash==1.0.2
    - nb2pdf==0.5.1
    - nbgitpuller==0.8.0
    - nbgrader
    - nbpdfexport==0.2.1
    - nltk==3.5
    - numexpr==2.7.1
    - otter-grader==1.0.0b9
    - pandas==1.1.2
    - patsy==0.5.1
    - pillow==7.2.0
    - plac==1.1.3
    - plotly==4.9.0
    - plotly-charts==0.5
    - plotly-geo==1.0.0
    - pluggy==0.13.1
    - preshed==3.0.2
    - psycopg2==2.8.6
    - py==1.9.0
    - pycodestyle==2.6.0
    - pyee==7.0.3
    - pyflakes==2.2.0
    - pyldavis==2.1.2
    - pyppeteer==0.2.2
    - pytest==6.0.2
    - python-jsonrpc-server==0.4.0
    - python-language-server==0.33.3
    - pytz==2020.1
    - pyyaml==5.3.1
    - qtconsole==4.7.7
    - qtpy==1.9.0
    - rapidfuzz==0.11.2
    - regex==2020.7.14
    - retrying==1.3.3
    - s3transfer==0.3.3
    - scikit-learn==0.23.2
    - scipy==1.5.2
    - seaborn==0.10.1
    - smart-open==2.1.1
    - spacy==2.3.2
    - srsly==1.0.2
    - statsmodels==0.12.0
    - thinc==7.4.1
    - threadpoolctl==2.1.0
    - toml==0.10.1
    - ujson==1.35
    - wasabi==0.8.0
    - websocket-client==0.57.0
    - websockets==8.1
    - werkzeug==1.0.1
    - widgetsnbextension==3.5.1
    - xgboost==1.1.1
    - yellowbrick==1.1
    - zope-interface==5.1.0

